version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka-net
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  python-consumer:
    build:
      context: .
      dockerfile: python-consumer/Dockerfile
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka-net
    restart: on-failure

  go-producer:
    build:
      context: .
      dockerfile: go-producer/Dockerfile
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka-net
    restart: on-failure

networks:
  kafka-net:
    driver: bridge
